# Generated by Django 6.1 on 2026-08-31 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('final_date', models.DateField()),
                ('application_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], max_length=20)),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'absences',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('final_time', models.TimeField()),
                ('period_number', models.IntegerField()),
            ],
            options={
                'db_table': 'class_time',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Sexto', 'Sexto'), ('Séptimo', 'Séptimo'), ('Octavo', 'Octavo'), ('Noveno', 'Noveno'), ('Décimo', 'Décimo'), ('Once', 'Once')], max_length=20)),
                ('section', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5)),
                ('classroom', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_absences',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('state', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=5)),
                ('absences', models.ForeignKey(db_column='absences_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.absence')),
            ],
            options={
                'db_table': 'availability',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('name1', models.CharField(max_length=20)),
                ('name2', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name1', models.CharField(max_length=20)),
                ('last_name2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassOne.city')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=6)),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.person')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('type_phone', models.CharField(choices=[('Celular', 'Celular'), ('Trabajo', 'Trabajo')], max_length=20)),
                ('person', models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.person')),
            ],
            options={
                'db_table': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_week', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('classtime', models.ForeignKey(db_column='classtime_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.classtime')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.course')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField()),
                ('state', models.CharField(choices=[('En Proceso', 'En Proceso'), ('Completado', 'Completado')], max_length=20)),
                ('absences', models.ForeignKey(db_column='absences_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.absence')),
                ('availability', models.ForeignKey(db_column='availability_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.availability')),
                ('schedule', models.ForeignKey(db_column='schedule_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.schedule')),
            ],
            options={
                'db_table': 'replacements',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordinador', 'Coordinador'), ('Rector', 'Rector')], max_length=20)),
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.person')),
            ],
            options={
                'db_table': 'staff_members',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.person')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.teacher'),
        ),
        migrations.AddField(
            model_name='availability',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.teacher'),
        ),
        migrations.AddField(
            model_name='absence',
            name='teacher',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherHasSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('Ciencias Naturales', 'Ciencias Naturales'), ('Ciencias Sociales', 'Ciencias Sociales'), ('Matemáticas', 'Matemáticas'), ('Artística', 'Artística'), ('Español', 'Español'), ('Ingles', 'Ingles'), ('Tecnología e Informática', 'Tecnología e Informática'), ('Ciencias Políticas', 'Ciencias Políticas'), ('Filosofía', 'Filosofía'), ('Religión', 'Religión'), ('Ética', 'Ética'), ('Educación Física', 'Educación Física')], max_length=50)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.subject')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.teacher')),
            ],
            options={
                'db_table': 'teachers_has_subject',
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='type_absences',
            field=models.ForeignKey(db_column='type_absences_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.typeabsence'),
        ),
    ]
