# Generated by Django 6.1 on 2026-09-07 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassOne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_state', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.CreateModel(
            name='SchoolAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coordinador', 'Coordinador'), ('Rector', 'Rector')], max_length=50)),
                ('person', models.OneToOneField(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, to='ClassOne.person')),
            ],
            options={
                'db_table': 'school_administrators',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(db_column='state_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='ClassOne.state'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
